config/routes.rb
KaisenNakaji::Application.routes.draw do
  devise_for :admins

  get "orders/index"

  resources :shops
  resources :orders

  get "store/index"
  get "store" => "store#index", :as => :store
  match "store/checkout", :as => :checkout
  post "store/add_to_cart/:id" => "store#add_to_cart"
  post "store/empty_cart" => "store#empty_cart"
  post "store/save_order" => "store#save_order", :as => :save_order
  
  get "orders/edit_order/:id" => "orders#edit_order"

  resources :products do
    collection do
      get "sold"
    end

    member do
      get "who_bought"
    end
  end

  root :to => "store#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KaisenNakaji</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <p class="notics"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/layouts/store.html.haml
!!! 5
%html
  %head
    %meta{ "http-qeuiv" => "Content-Type", :content => "text/html: charset=utf8" }
    %title 買鮮カタログ
    != stylesheet_link_tag 'reset', 'text', '960', 'store', 'screen'
    != javascript_include_tag :defaults
    != csrf_meta_tag
  %body#store.container_12
    %div#header.grid_12
      %h1 買鮮カタログ
    .clear
    #colmuns

      #main.grid_5.suffix_2
        - if flash[:notice]
          #notice= flash[:notice]
        - if flash[:alert]
          #alert= flash[:alert]
        != yield
      #side.grid_5
        - if @cart
          #cart
            = render :partial => 'cart', :object => @cart
        %ul#nav
          %li
            = link_to "トップ", store_path
          %li
            %a{:href => "#"}ニュース
          %li
            %a{:href => "#"}お問合わせ
          %li
            %a{:href => "#"}ご利用ガイド

        - if admin_signed_in?
          %div.title
            管理メニュー

          %ul#nav
            %li
              = link_to "商品管理", products_path
            %li
              = link_to "注文情報管理", orders_path
            %li
              = link_to "ログアウト", destroy_admin_session_path

      .clear
    #footer.grid_12
      %p Copyright (C) 2010 Enishi Tech Inc. AllRights Reserved.
    .clear